# Generated by Django 4.1.3 on 2022-12-07 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkAttendance', '0002_alter_attendance_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 7, 6, 1, 16, 470200, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
